name: çœ‹çœ‹è¿™é‡Œ ğŸ‘‰

on: [pull_request]

jobs:
  run-ci:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    name: ğŸ‘Œ Automated Machine
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ¦¹â€â™€ï¸ è¶…çº§åæ´¾å¥³äºº
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: ğŸ‘¼ å¤©ä½¿
        run: npm test